(require 'calendar)
(require 'solar)
(require 'cl-lib)

; Output from this code matches that of Python code (sayana-panchanga.py) exactly!
; This code is generated by Google Gemini and slightly adapted
; Also matches the output in Dieter Koch's https://www.gilgamesh.ch/kalender/kalender.html

(defconst solar-rasis '("Mesha" "Vrishabha" "Mithuna" "Karka" "Simha"
  "Kanya" "Tula" "Vrishchika" "Dhanus" "Makara" "Kumbha" "Meena"))

(defun get-solar-longitude (gregorian-date ut-hour &optional sidereal-p)
  "Get true ecliptic longitude for a Gregorian DATE (month day year) and UT hour.
If SIDEREAL-P is non-nil, returns Nirayana (sidereal) longitude using Lahiri Ayanamsha.
Otherwise, returns Sayana (tropical) longitude."
  (let* ((julian-centuries (solar-date-to-et gregorian-date ut-hour))
         (coords (solar-ecliptic-coordinates julian-centuries t))
         (tropical-long (car coords)))
    (if sidereal-p
        ;; Apply linear approximation of Lahiri Ayanamsha
        ;; Base Ayanamsha at J2000.0 (Jan 1, 2000) is ~23.85°
        ;; Average rate of precession is ~1.39604° per Julian century
        (let* ((ayanamsha (+ 23.85709 (* julian-centuries 1.39604)))
               (sidereal-long (- tropical-long ayanamsha)))
          (mod sidereal-long 360.0))
      (mod tropical-long 360.0))))

(defun calculate-gregorian-from-solar (year month-name solar-day &optional sidereal-p)
  "Convert a Sayana or Nirayana solar date to a Gregorian date.
YEAR is the primary Gregorian year of the cycle.
MONTH-NAME is the solar Rasi (e.g., \"Mesha\").
SOLAR-DAY is the integer day of the solar month.
If SIDEREAL-P is non-nil, calculates against the Nirayana (sidereal) framework.

; Example execution (Sayana):
(calculate-gregorian-from-solar 2026 \"Mesha\" 15)

; Example execution (Nirayana):
(calculate-gregorian-from-solar 2026 \"Mesha\" 15 t)
"
  (let* ((target-rasi-idx (cl-position month-name solar-rasis :test 'string=))
         ;; Determine safe search start date (absorbs both Sayana and Nirayana variance)
         ;; (1-2 months before expected Sankranti)
         (start-month (nth target-rasi-idx '(2 3 4 5 6 7 8 9 10 11 12 1)))
         ;; Kumbha (idx 10) occurs early in the year, so we start searching in Dec of the prior year.
         (start-year (if (= target-rasi-idx 10) (1- year) year))
         (current-abs (calendar-absolute-from-gregorian (list start-month 1 start-year))))

    (unless target-rasi-idx
      (error "Invalid solar month name: %s" month-name))

    ;; Step forward until 00:00 UT falls into the target Rasi
    (while (/= (floor (/ (get-solar-longitude
                          (calendar-gregorian-from-absolute current-abs)
                          0.0    ;; midnight-to-midnight
                          sidereal-p)
                         30.0))  ;; Each rasi spans 30°
               target-rasi-idx)
      (setq current-abs (1+ current-abs)))

    ;; Apply the Day 1 offset
    ;; If the sun is in the target Rasi at 00:00 UT on current-abs,
    ;; the transition (Sankranti) occurred on the previous day.
    (let* ((day-one (1- current-abs))
           (target-abs (+ day-one (1- solar-day)))
           (result-greg (calendar-gregorian-from-absolute target-abs))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

  (message "%s Input: %s %d, %04d | Gregorian Result: %04d-%02d-%02d"
           system-name month-name solar-day year
           (nth 2 result-greg) (nth 0 result-greg) (nth 1 result-greg)))))


(defun calculate-solar-from-gregorian (year month day ut-hour &optional sidereal-p)
  "Calculate the Sayana or Nirayana month and day for a Gregorian date and UT time.
If SIDEREAL-P is non-nil, calculates against the Nirayana (sidereal) framework.

; Example execution (Sayana):
(calculate-solar-from-gregorian 2026 3 17 14.0)

Example execution (Nirayana):
(calculate-solar-from-gregorian 2026 3 17 14.0 t)
"
  (let* ((gregorian-date (list month day year))
         (target-abs-date (calendar-absolute-from-gregorian gregorian-date))

         ;; 1. Get current longitude and determine the Rasi index
         (current-long (get-solar-longitude gregorian-date ut-hour sidereal-p))
         (target-rasi-idx (floor (/ current-long 30.0)))

         ;; 2. Search backward at 00:00 UT to find the Sankranti day
         (sankranti-abs-date target-abs-date)
         ;; Increased search limit to 35 safely covers maximum Nirayana month length
         ;; Though a tropical solar month is normally 29-32 days
         (search-limit (- target-abs-date 35)))

    (while (and (> sankranti-abs-date search-limit)
                (= (floor (/ (get-solar-longitude
                              (calendar-gregorian-from-absolute sankranti-abs-date)
                              0.0 ; midnight-to-midnight
                              sidereal-p)
                             30.0))
                   target-rasi-idx))
      (setq sankranti-abs-date (1- sankranti-abs-date)))

    ;; 3. Calculate the day (Sankranti day itself is Day 1)
    (let* ((day-one sankranti-abs-date)
           (solar-day (1+ (- target-abs-date day-one)))
           (rasi-name (nth target-rasi-idx solar-rasis))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

      (message "Gregorian Date: %04d-%02d-%02d %02d:00 UT | %s Date: %s %d | Longitude: %.2f°"
               year month day ut-hour
               system-name rasi-name solar-day
               current-long))))
