(require 'calendar)
(require 'solar)
(require 'cl-lib)

; Output from this code matches that of Python code (sayana-panchanga.py) exactly!
; This code is generated by Google Gemini and slightly adapted
; Also matches the output in Dieter Koch's https://www.gilgamesh.ch/kalender/kalender.html

(defconst solar-rasis '("Mesha" "Vrishabha" "Mithuna" "Karka" "Simha"
  "Kanya" "Tula" "Vrishchika" "Dhanus" "Makara" "Kumbha" "Meena"))

(defun get-solar-longitude (gregorian-date ut-hour &optional sidereal-p)
  "Get true ecliptic longitude for a Gregorian DATE (month day year) and UT hour.
If SIDEREAL-P is non-nil, returns Nirayana (sidereal) longitude using Lahiri Ayanamsha.
Otherwise, returns Sayana (tropical) longitude."
  (let* ((julian-centuries (solar-date-to-et gregorian-date ut-hour))
         (coords (solar-ecliptic-coordinates julian-centuries t))
         (tropical-long (car coords)))
    (if sidereal-p
        ;; Apply linear approximation of Lahiri Ayanamsha
        ;; Base Ayanamsha at J2000.0 (Jan 1, 2000) is ~23.85°
        ;; Average rate of precession is ~1.39604° per Julian century
        (let* ((ayanamsha (+ 23.85709 (* julian-centuries 1.39604)))
               (sidereal-long (- tropical-long ayanamsha)))
          (mod sidereal-long 360.0))
      (mod tropical-long 360.0))))

(defun calculate-gregorian-from-solar (year month-name solar-day &optional sidereal-p)
  "Convert a Sayana or Nirayana solar date to a Gregorian date.
YEAR is the primary Gregorian year of the cycle.
MONTH-NAME is the solar Rasi (e.g., \"Mesha\").
SOLAR-DAY is the integer day of the solar month.
If SIDEREAL-P is non-nil, calculates against the Nirayana (sidereal) framework.

; Example execution (Sayana):
(calculate-gregorian-from-solar 2026 \"Mesha\" 15)

; Example execution (Nirayana):
(calculate-gregorian-from-solar 2026 \"Mesha\" 15 t)
"
  (let* ((target-rasi-idx (cl-position month-name solar-rasis :test 'string=))
         ;; Determine safe search start date (absorbs both Sayana and Nirayana variance)
         ;; (1-2 months before expected Sankranti)
         (start-month (nth target-rasi-idx '(2 3 4 5 6 7 8 9 10 11 12 1)))
         ;; Kumbha (idx 10) occurs early in the year, so we start searching in Dec of the prior year.
         (start-year (if (= target-rasi-idx 10) (1- year) year))
         (current-abs (calendar-absolute-from-gregorian (list start-month 1 start-year))))

    (unless target-rasi-idx
      (error "Invalid solar month name: %s" month-name))

    ;; Step forward until 00:00 UT falls into the target Rasi
    (while (/= (floor (/ (get-solar-longitude
                          (calendar-gregorian-from-absolute current-abs)
                          0.0    ;; midnight-to-midnight
                          sidereal-p)
                         30.0))  ;; Each rasi spans 30°
               target-rasi-idx)
      (setq current-abs (1+ current-abs)))

    ;; Apply the Day 1 offset
    ;; If the sun is in the target Rasi at 00:00 UT on current-abs,
    ;; the transition (Sankranti) occurred on the previous day.
    (let* ((day-one (1- current-abs))
           (target-abs (+ day-one (1- solar-day)))
           (result-greg (calendar-gregorian-from-absolute target-abs))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

  (message "%s Input: %s %d, %04d | Gregorian Result: %04d-%02d-%02d"
           system-name month-name solar-day year
           (nth 2 result-greg) (nth 0 result-greg) (nth 1 result-greg)))))


(defun calculate-solar-from-gregorian (year month day ut-hour &optional sidereal-p)
  "Calculate the Sayana or Nirayana month and day for a Gregorian date and UT time.
If SIDEREAL-P is non-nil, calculates against the Nirayana (sidereal) framework.

; Example execution (Sayana):
(calculate-solar-from-gregorian 2026 3 17 14.0)

Example execution (Nirayana):
(calculate-solar-from-gregorian 2026 3 17 14.0 t)
"
  (let* ((gregorian-date (list month day year))
         (target-abs-date (calendar-absolute-from-gregorian gregorian-date))

         ;; 1. Get current longitude and determine the Rasi index
         (current-long (get-solar-longitude gregorian-date ut-hour sidereal-p))
         (target-rasi-idx (floor (/ current-long 30.0)))

         ;; 2. Search backward at 00:00 UT to find the Sankranti day
         (sankranti-abs-date target-abs-date)
         ;; Increased search limit to 35 safely covers maximum Nirayana month length
         ;; Though a tropical solar month is normally 29-32 days
         (search-limit (- target-abs-date 35)))

    (while (and (> sankranti-abs-date search-limit)
                (= (floor (/ (get-solar-longitude
                              (calendar-gregorian-from-absolute sankranti-abs-date)
                              0.0 ; midnight-to-midnight
                              sidereal-p)
                             30.0))
                   target-rasi-idx))
      (setq sankranti-abs-date (1- sankranti-abs-date)))

    ;; 3. Calculate the day (Sankranti day itself is Day 1)
    (let* ((day-one sankranti-abs-date)
           (solar-day (1+ (- target-abs-date day-one)))
           (rasi-name (nth target-rasi-idx solar-rasis))
           (system-name (if sidereal-p "Nirayana" "Sayana")))

      (message "Gregorian Date: %04d-%02d-%02d %02d:00 UT | %s Date: %s %d | Longitude: %.2f°"
               year month day ut-hour
               system-name rasi-name solar-day
               current-long))))

(require 'lunar)

(defconst lunar-months '("Vaisakha" "Jyeshtha" "Ashadha" "Shravana"
  "Bhadrapada" "Ashvina" "Kartika" "Margashirsha" "Pausha" "Magha"
  "Phalguna" "Chaitra"))

(defun parse-calendar-time (time-val)
  "Parse Emacs time string (e.g., '3:26 PM (EET)' or '15:26') to fractional hours."
  (if (numberp time-val)
      time-val
    (if (string-match "\\([0-9]+\\):\\([0-9]+\\)\\s-*\\([aApP][mM]\\)?" time-val)
        (let ((hour (string-to-number (match-string 1 time-val)))
              (minute (string-to-number (match-string 2 time-val)))
              (am-pm (match-string 3 time-val)))
          ;; Handle 12-hour AM/PM shifts
          (when (and am-pm (string-match-p "[pP]" am-pm) (< hour 12))
            (setq hour (+ hour 12)))
          (when (and am-pm (string-match-p "[aA]" am-pm) (= hour 12))
            (setq hour 0))
          (+ hour (/ minute 60.0)))
      0.0))) ; Fallback boundary


(defun get-sunrise-ut (gregorian-date fallback-ut)
  "Calculate sunrise in UT for GREGORIAN-DATE using Emacs location settings.
Defaults to Ujjain, India if calendar coordinates are unset.
Falls back to FALLBACK-UT if no sunrise exists (e.g., polar night/day)."
  (let* ((calendar-latitude (if (bound-and-true-p calendar-latitude)
                                calendar-latitude
                              23.1765))
         (calendar-longitude (if (bound-and-true-p calendar-longitude)
                                 calendar-longitude
                               75.7885))
         (calendar-time-zone (if (bound-and-true-p calendar-time-zone)
                                 calendar-time-zone
                               330)) ; +5:30 IST in minutes

         (sun-data (solar-sunrise-sunset gregorian-date))
         (sunrise-local (and sun-data (car (car sun-data)))))

    (if (numberp sunrise-local)
        (- sunrise-local (/ calendar-time-zone 60.0))
      fallback-ut)))

(defun calculate-lunar-from-gregorian (year month day fallback-ut &optional sidereal-p)
  "Calculate the traditional lunar month, Paksha, and Madhyama Tithi at local sunrise.
If SIDEREAL-P is non-nil, calculates using Nirayana solar longitude."
  (let* ((target-date (list month day year))
         (target-abs (calendar-absolute-from-gregorian target-date))

         ;; 1. Fetch Sunrise UT
         (target-ut-hour (get-sunrise-ut target-date fallback-ut))
         (target-abs-time (+ target-abs (/ target-ut-hour 24.0)))

         ;; Shift search window backward safely
         (search-month (if (= month 1) 12 (1- month)))
         (search-year (if (= month 1) (1- year) year))
         (phases (lunar-phase-list search-month search-year))
         new-moons prev-nm next-nm)

    ;; 2. Extract and sort all New Moons (Phase 0)
    (dolist (p phases)
      (when (= (nth 2 p) 0)
        (let* ((p-date (nth 0 p))
               (p-time (parse-calendar-time (nth 1 p)))
               (p-abs (+ (calendar-absolute-from-gregorian p-date)
                         (/ p-time 24.0))))
          (push p-abs new-moons))))
    (setq new-moons (sort new-moons '<))

    ;; 3. Find the bounding New Moons for the target date
    (catch 'found
      (let ((i 0)
            (len (1- (length new-moons))))
        (while (< i len)
          (let ((t1 (nth i new-moons))
               (t2 (nth (1+ i) new-moons)))
            (when (and (>= target-abs-time t1) (< target-abs-time t2))
              (setq prev-nm t1
                    next-nm t2)
              (throw 'found t)))
          (setq i (1+ i)))))

    (if (not (and prev-nm next-nm))
        (error "Could not bound the target date between two New Moons.")

      ;; 4. Calculate Madhyama Tithi and Paksha
      (let* ((cycle-length (- next-nm prev-nm))
             (tithi-length (/ cycle-length 30.0))
             (elapsed (- target-abs-time prev-nm))
             (tithi-idx (1+ (floor (/ elapsed tithi-length))))
             (paksha (if (<= tithi-idx 15) "Shukla" "Krishna"))
             (tithi-num (if (> tithi-idx 15) (- tithi-idx 15) tithi-idx))

             ;; 5. Evaluate Sun's longitude at both New Moon boundaries
             (nm1-abs-date (truncate prev-nm))
             (nm1-ut-hour (* (- prev-nm nm1-abs-date) 24.0))
             (nm1-greg-date (calendar-gregorian-from-absolute nm1-abs-date))
             (sun-long-start (get-solar-longitude nm1-greg-date nm1-ut-hour sidereal-p))

             (nm2-abs-date (truncate next-nm))
             (nm2-ut-hour (* (- next-nm nm2-abs-date) 24.0))
             (nm2-greg-date (calendar-gregorian-from-absolute nm2-abs-date))
             (sun-long-end (get-solar-longitude nm2-greg-date nm2-ut-hour sidereal-p))

             ;; 6. Determine Lunar Month and Adhika flag
             (rasi-idx-start (floor (/ sun-long-start 30.0)))
             (rasi-idx-end (floor (/ sun-long-end 30.0)))
             (is-adhika (= rasi-idx-start rasi-idx-end))

             (base-month-name (nth rasi-idx-start lunar-months))
             (lunar-month-name (if is-adhika
                                   (concat "Adhika " base-month-name)
                                 base-month-name))
             (system-name (if sidereal-p "Nirayana" "Sayana")))

        (message "%s | Date: %04d-%02d-%02d | Sunrise UT: %.2f | %s %s %d"
                 system-name year month day target-ut-hour
                 lunar-month-name paksha tithi-num)))))
