#!/usr/bin/env python3

# Code generated by Google Gemini

import datetime
from skyfield.api import load, wgs84
from skyfield import almanac

# Load ephemeris
ts = load.timescale()
eph = load('de421.bsp')
earth, sun = eph['earth'], eph['sun']

rasis_sayana = [ "Mesha > 0°", "Vrishabha > 30°", "Mithuna > 60°",
                 "Karka > 90°", "Simha > 120°", "Kanya > 150°", "Tula > 180°",
                 "Vrishchika > 210°", "Dhanus > 240°", "Makara > 270°",
                 "Kumbha > 300°", "Meena > 330°", ]

def gregorian_to_sayana_transit(year, month, day, hour, minute, second, lat, lon_deg):
    target_t = ts.utc(year, month, day, hour, minute, second)

    # 1. Ecliptic Longitude (Sayana)
    apparent = earth.at(target_t).observe(sun).apparent()
    _, lon, _ = apparent.ecliptic_latlon(epoch='date')
    current_deg = lon.degrees
    month_idx = int(current_deg // 30)

    # 2. Find previous Sankranti
    t0_datetime = target_t.utc_datetime() - datetime.timedelta(days=32)
    t0 = ts.utc(t0_datetime.year, t0_datetime.month, t0_datetime.day)

    def sankranti_state(t):
        app = earth.at(t).observe(sun).apparent()
        _, l, _ = app.ecliptic_latlon(epoch='date')
        return (l.degrees // 30).astype(int)

    sankranti_state.step_days = 1.0

    times, states = almanac.find_discrete(t0, target_t, sankranti_state)

    if len(times) == 0:
        return "Error: Could not locate previous Sankranti."

    sankranti_time = times[-1]

    # 3. Calculate Days using Lower Transits (Solar Midnight)
    observer = wgs84.latlon(lat, lon_deg)
    f = almanac.meridian_transits(eph, sun, observer)

    # Find all transits between Sankranti and Target Date
    transit_times, transit_flags = almanac.find_discrete(sankranti_time, target_t, f)

    # Count only Lower Transits (Anti-meridian / Solar Midnight). Flag 0 = Lower, 1 = Upper
    lower_transits = sum(1 for flag in transit_flags if flag == 0)

    # Day 1 starts at the exact moment of Sankranti.
    # Each subsequent lower transit increments the day.
    sayana_day = lower_transits + 1

    return {
        "Gregorian Date": target_t.utc_strftime('%Y-%m-%d %H:%M:%S UTC'),
        "Sayana Month": rasis_sayana[month_idx],
        "Sayana Day": sayana_day,
        "Degrees": round(current_deg, 4),
        "Lower Transits Elapsed": lower_transits
    }

if __name__ == "__main__":
    # Coordinates for Espoo, Finland
    lat = 69.0443
    lon = 20.8033

    # Target: March 17, 2026 at 14:35:56 UTC
    result = gregorian_to_sayana_transit(2026, 1, 1, 14, 35, 56, lat, lon)

    for key, value in result.items():
        print(f"{key}: {value}")
